[package]
name = "hoi4_build_core"
version = "0.1.1"
edition = "2024"

[lib]
name = "hoi4_build_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module", "abi3-py310"] }
smallvec = "1.13"
rapidhash = "4.1.1"
orx-priority-queue = "=1.7.0"

[dev-dependencies]
proptest = "1.4"
